set ARM_CLIENT_ID=INSERT_GUID_HERE
set ARM_SUBSCRIPTION_ID=INSERT_GUID_HERE
set ARM_TENANT_ID=INSERT_GUID_HERE
set ARM_CLIENT_SECRET=INSERT_SERCRET_HERE


export ARM_CLIENT_ID=INSERT_GUID_HERE
export ARM_SUBSCRIPTION_ID=INSERT_GUID_HERE
export ARM_TENANT_ID=INSERT_GUID_HERE
export ARM_CLIENT_SECRET=INSERT_SERCRET_HERE

cd terraform #if not alredy

terraform init


terraform state list
