apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whisper-web-client
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - whisper.dankapps.app
    secretName: dankapps-app-gcloud-dns-tls
  rules:
  - host: whisper.dankapps.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whisper-web-client
            port:
              number: 80
