apiVersion: batch/v1
kind: CronJob
metadata:
  name: azure-lb-updater
  namespace: default
spec:
  schedule: "0 0 * * *"  # Runs once a day; adjust as necessary
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: azure-lb-updater
            image: 192.168.8.129:32000/update-lb-cron:1.0.68
            env:
              - name: AZURE_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: azure-credentials
                    key: client-id
              - name: AZURE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: azure-credentials
                    key: client-secret
              - name: AZURE_TENANT_ID
                valueFrom:
                  secretKeyRef:
                    name: azure-credentials
                    key: tenant-id
              - name: AZURE_SUBSCRIPTION
                valueFrom:
                  secretKeyRef:
                    name: azure-credentials
                    key: subscription-id
            args:
              - "zambonigirl.com"  # Replace with your DNS name
          restartPolicy: OnFailure
