apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paintedravendesign-shopstr-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed